# Generated by Django 4.2.7 on 2025-08-30 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='权限代码')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('category', models.CharField(choices=[('system', '系统管理'), ('user', '用户管理'), ('trading', '交易管理'), ('strategy', '策略管理'), ('risk', '风险控制'), ('market', '市场数据'), ('monitoring', '系统监控')], max_length=20, verbose_name='权限分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'core_permission',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='租户名称')),
                ('schema_name', models.CharField(max_length=63, unique=True, verbose_name='数据库模式名')),
                ('domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='域名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('max_users', models.PositiveIntegerField(default=100, verbose_name='最大用户数')),
                ('max_strategies', models.PositiveIntegerField(default=50, verbose_name='最大策略数')),
                ('max_exchange_accounts', models.PositiveIntegerField(default=10, verbose_name='最大交易所账户数')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='订阅到期时间')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'core_tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('role_type', models.CharField(choices=[('system', '系统预定义'), ('custom', '自定义角色')], default='custom', max_length=10, verbose_name='角色类型')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='优先级')),
                ('color', models.CharField(default='#1890FF', max_length=7, verbose_name='颜色标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='core.role', verbose_name='父角色')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission', verbose_name='权限')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'core_role',
                'ordering': ['-priority', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('title', models.CharField(max_length=100, verbose_name='显示标题')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路径')),
                ('component', models.CharField(blank=True, max_length=200, verbose_name='组件')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('menu_type', models.CharField(choices=[('menu', '菜单'), ('button', '按钮'), ('link', '链接')], default='menu', max_length=10, verbose_name='菜单类型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menu', verbose_name='父菜单')),
                ('required_permissions', models.ManyToManyField(blank=True, help_text='用户需要拥有这些权限才能看到此菜单', to='core.permission', verbose_name='所需权限')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'core_menu',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
