# Generated by Django 4.2.7 on 2025-08-30 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermissionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_permissions', models.JSONField(default=dict, verbose_name='菜单权限')),
                ('cache_time', models.DateTimeField(auto_now=True, verbose_name='缓存时间')),
            ],
            options={
                'verbose_name': '菜单权限缓存',
                'verbose_name_plural': '菜单权限缓存',
                'db_table': 'core_menu_permission_cache',
            },
        ),
        migrations.CreateModel(
            name='UserMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('custom_title', models.CharField(blank=True, max_length=100, verbose_name='自定义标题')),
                ('custom_icon', models.CharField(blank=True, max_length=100, verbose_name='自定义图标')),
                ('custom_sort', models.PositiveIntegerField(default=0, verbose_name='自定义排序')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
                ('last_access_time', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '用户菜单配置',
                'verbose_name_plural': '用户菜单配置',
                'db_table': 'core_user_menu_config',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['level', 'sort_order', 'id'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_cache',
            field=models.BooleanField(default=True, verbose_name='是否缓存'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='菜单层级'),
        ),
        migrations.AddField(
            model_name='menu',
            name='meta_info',
            field=models.JSONField(blank=True, default=dict, help_text='存储额外的菜单配置信息', verbose_name='元信息'),
        ),
        migrations.AddField(
            model_name='menu',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='所需权限'),
        ),
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.role', verbose_name='可访问角色'),
        ),
        migrations.AddField(
            model_name='menu',
            name='target',
            field=models.CharField(choices=[('_self', '当前窗口'), ('_blank', '新窗口')], default='_self', max_length=20, verbose_name='打开方式'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=200, verbose_name='组件路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, help_text='图标类名或图标代码', max_length=100, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('menu', '菜单'), ('button', '按钮'), ('link', '链接')], default='menu', max_length=20, verbose_name='菜单类型'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=200, verbose_name='路由路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='菜单标题'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['tenant', 'parent', 'level'], name='core_menu_tenant__529af1_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['tenant', 'is_visible', 'is_enabled'], name='core_menu_tenant__886543_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['tenant', 'sort_order'], name='core_menu_tenant__839a24_idx'),
        ),
        migrations.AddField(
            model_name='usermenuconfig',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu', verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='usermenuconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='usermenuconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='menupermissioncache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='required_permissions',
        ),
        migrations.AddIndex(
            model_name='usermenuconfig',
            index=models.Index(fields=['tenant', 'user', 'is_favorite'], name='core_user_m_tenant__42972b_idx'),
        ),
        migrations.AddIndex(
            model_name='usermenuconfig',
            index=models.Index(fields=['tenant', 'user', 'is_hidden'], name='core_user_m_tenant__f9f959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermenuconfig',
            unique_together={('tenant', 'user', 'menu')},
        ),
        migrations.AlterUniqueTogether(
            name='menupermissioncache',
            unique_together={('user',)},
        ),
    ]
